alexandre_collet/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('cv.urls')),
    url(r'^admin/', admin.site.urls),
]


handler400 = 'cv.views.error400'
handler403 = 'cv.views.error403'
handler404 = 'cv.views.error404'
handler500 = 'cv.views.error500'

cv/urls.py
from django.conf.urls import url

from cv.views import IndexView, ContactView

app_name = 'cv'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^contact/$', ContactView.as_view(), name='contact')
]

cv/models.py
from django.db.models import (
    Model, CASCADE,
    BooleanField, DateField, CharField, URLField, TextField, IntegerField,
    PositiveSmallIntegerField, ImageField, FileField, ForeignKey
)
from django.utils.text import slugify

from ordered_model.models import OrderedModel

from cv.decorators import UploadToPathAndRename


class Resume(Model):
    firstname = CharField(max_length=50)
    lastname = CharField(max_length=50)
    title = CharField(max_length=200, null=True, blank=True)
    summary = TextField(null=True, blank=True)
    photo = ImageField(
        null=True,
        blank=True,
        upload_to=UploadToPathAndRename('cv/resumes/photos'),
    )
    pdf_file = FileField(
        null=True,
        blank=True,
        upload_to=UploadToPathAndRename('cv/resumes/pdfs'),
    )

    github = URLField(blank=True, null=True)
    docker = URLField(blank=True, null=True)
    linkedin = URLField(blank=True, null=True)
    twitter = URLField(blank=True, null=True)

    def __str__(self):
        return self.fullname

    @property
    def fullname(self):
        return self.get_fullname()

    def get_fullname(self):
        fullname_format_string = "{firstname} {lastname}"
        fullname_kwargs = {
            'firstname': self.firstname,
            'lastname': self.lastname,
        }

        return fullname_format_string.format(**fullname_kwargs)


class Project(OrderedModel):
    name = CharField(max_length=50, unique=True)
    description = TextField(blank=True)

    @property
    def slug(self):
        return slugify(self.name)

    def __str__(self):
        return self.name

    class Meta(OrderedModel.Meta):
        pass


class ProjectLink(OrderedModel):
    project = ForeignKey(
        'Project',
        related_name='links', on_delete=CASCADE
    )
    name = CharField(max_length=50)
    url = URLField(unique=True)
    icon = CharField(max_length=10, blank=True)

    def __str__(self):
        return self.project.name + ' - ' + self.name

    class Meta(OrderedModel.Meta):
        unique_together = ('project', 'name')
        ordering = ('project', 'order')
        verbose_name_plural = 'Project Links'


class ProjectTechnology(OrderedModel):
    project = ForeignKey(
        'Project',
        related_name='technologies', on_delete=CASCADE
    )
    name = CharField(max_length=50)

    def __str__(self):
        return self.project.name + ' - ' + self.name

    class Meta(OrderedModel.Meta):
        unique_together = ('project', 'name')
        ordering = ('project', 'order')
        verbose_name_plural = 'Project Technologies'


class ProjectScreenshot(OrderedModel):
    project = ForeignKey(
        'Project',
        related_name='screenshots', on_delete=CASCADE
    )
    name = CharField(max_length=255)
    image = ImageField(
        upload_to=UploadToPathAndRename('cv/projects/screenshots')
    )

    def __str__(self):
        return self.project.name + ' - ' + self.name

    class Meta(OrderedModel.Meta):
        unique_together = ('project', 'name')
        ordering = ('project', 'order')
        verbose_name_plural = 'Project Screenshots'


class Skill(OrderedModel):
    name = CharField(max_length=50, unique=True)
    level = PositiveSmallIntegerField()
    main = BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta(OrderedModel.Meta):
        ordering = ('main', 'order', 'level')


class Experience(Model):
    CATEGORY_JOB = 0
    CATEGORY_EDUCATION = 1
    CATEGORY_VOLUNTEERING = 2

    CATEGORY_CHOICES = (
        (CATEGORY_JOB, 'Job'),
        (CATEGORY_EDUCATION, 'Education'),
        (CATEGORY_VOLUNTEERING, 'Volunteering'),
    )

    name = CharField(max_length=50, unique=True)
    category = IntegerField(default=CATEGORY_JOB, choices=CATEGORY_CHOICES)
    date_start = DateField()
    date_stop = DateField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-date_start', )


class ExperienceActivity(OrderedModel):
    experience = ForeignKey(
        'Experience',
        related_name='activities', on_delete=CASCADE
    )
    description = TextField()

    def __str__(self):
        return self.experience.name + ': ' + self.description[:10]

    class Meta(OrderedModel.Meta):
        ordering = ('experience', 'order')
        verbose_name_plural = 'Experience Activities'

cv/forms.py
from django.conf import settings
from django.forms import Form
from django.forms import CharField, EmailField
from django.forms import Textarea
from django.core.mail import EmailMessage


class ContactForm(Form):
    full_name = CharField(label='Full name', min_length=2, max_length=100)
    email = EmailField(label='Email')
    message = CharField(label='Message', widget=Textarea)

    def send_email(self):
        full_name = self.cleaned_data['full_name']
        subject = (
            "Message de " + full_name + " "
            "envoyé depuis le formulaire de contact"
        )
        message = self.cleaned_data['message']
        from_email = '{full_name} <{email}>'.format(
            full_name=full_name,
            email=settings.EMAIL_SENDER
        )
        recipient_list = [settings.EMAIL_RECIPIENT]
        reply_to_list = [self.cleaned_data['email']]

        email = EmailMessage(subject, message)
        email.subject = subject
        email.body = message
        email.from_email = from_email
        email.to = recipient_list
        email.reply_to = reply_to_list

        try:
            email.send()
        except:
            return False

        return True

cv/views.py
from django.conf import settings
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.decorators.csrf import requires_csrf_token
from django.template import loader
from django.http import (
    HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotFound,
    HttpResponseServerError, JsonResponse
)

from github import Github

from cv.models import Resume, Skill, Experience, Project
from cv.forms import ContactForm


class IndexView(TemplateView):
    http_method_names = ['get']
    template_name = 'cv/index.html'

    def get_context_data(self, **kwargs):
        github_client = Github(settings.GITHUB_TOKEN)

        context = {}
        context['resume'] = Resume.objects.first()
        context['repositories'] = github_client.get_user().get_repos()
        context['projects'] = Project.objects.all().prefetch_related(
            'technologies', 'links', 'screenshots'
        )
        context['skills'] = {
            'mains': Skill.objects.filter(main=True).all(),
            'others': Skill.objects.filter(main=False).all(),
        }
        context['experiences'] = {
            'job': Experience.objects.filter(
                category=Experience.CATEGORY_JOB).all(),
            'volunteering': Experience.objects.filter(
                category=Experience.CATEGORY_VOLUNTEERING).all(),
            'education': Experience.objects.filter(
                category=Experience.CATEGORY_EDUCATION).all(),
        }
        context['contact_form'] = ContactForm(
            auto_id='contact_form_%s_field', label_suffix=''
        )

        return context


class ContactView(FormView):
    http_method_names = ['post']
    form_class = ContactForm

    def form_valid(self, form):
        email_sent = form.send_email()

        if email_sent:
            response = {
                'type': 'success',
                'message': 'Message envoyé avec succès.'
            }
        else:
            response = {
                'type': 'error',
                'message': 'Une erreur est survenue.'
            }

        return JsonResponse(response)

    def form_invalid(self, form):
        response = {
            'type': 'error',
            'message': 'Tous les champs ne sont pas valides.'
        }
        return JsonResponse(response)


@requires_csrf_token
def error400(request, exception):
    template_name = 'cv/error.html'
    context = {
        'error_code': 400,
        'error_detail': 'Bad Request.'
    }

    template = loader.get_template(template_name)
    body = template.render(context, request)

    return HttpResponseBadRequest(body)


@requires_csrf_token
def error403(request, exception):
    template_name = 'cv/error.html'
    context = {
        'error_code': 403,
        'error_detail': 'Forbidden.'
    }

    template = loader.get_template(template_name)
    body = template.render(context, request)

    return HttpResponseForbidden(body)


@requires_csrf_token
def error404(request, exception):
    template_name = 'cv/error.html'
    context = {
        'error_code': 404,
        'error_detail': 'Page not found.'
    }

    template = loader.get_template(template_name)
    body = template.render(context, request)

    return HttpResponseNotFound(body)


@requires_csrf_token
def error500(request):
    template_name = 'cv/error.html'
    context = {
        'error_code': 500,
        'error_detail': 'Server error.'
    }

    template = loader.get_template(template_name)
    body = template.render(context, request)

    return HttpResponseServerError(body)

cv/templates/cv/sections/contact.html
<section id="contact">
    <h3>Comment me contacter ?</h3>
    <section id="social">
        <h4>Sur les réseaux sociaux</h4>
        {% if resume.linkedin %}
            <a href="{{ resume.linkedin }}" class="btn btn-red btn-icon-linkedin" title="Se rendre sur mon profil Linkedin">Linkedin</a>
        {% endif %}
        {% if resume.github %}
            <a href="{{ resume.github }}" class="btn btn-red btn-icon-github" title="Se rendre sur mon profil Github">Github</a>
        {% endif %}
        {% if resume.docker %}
            <a href="{{ resume.docker }}" class="btn btn-red btn-icon-docker" title="Se rendre sur mon profil Docker">Docker</a>
        {% endif %}
        {% if resume.twitter %}
            <a href="{{ resume.twitter }}" class="btn btn-red btn-icon-twitter" title="Se rendre sur mon profil Twitter">Twitter</a>
        {% endif %}
    </section>
    <form id="contact_form" action="{% url 'cv:contact' %}" method="POST">
        <h4>Par email</h4>
        {% csrf_token %}
        {{ contact_form.as_p }}
        <div id="contact_form_unlocker" class="unlocker">
            <p>Envoyer</p>
            <div class="thumb"></div>
        </div>
        <input type="submit" id="contact_form_submit">
    </form>
</section>

cv/templates/cv/sections/cv.html
<section id="cv">
    <h3>Quel est mon parcours ?</h3>

    <section id="skills">
        <div>
            <h4>Compétences</h4>
            {% for skill_main in skills.mains %}
                <div class="skill_primary bar bar-{{ skill_main.level }}">
                    <div>
                        <h5>{{ skill_main.name }}</h5>
                    </div>
                </div>
            {% endfor %}
            <div class="skills_secondary">
                {% for skill_other in skills.others %}
                    <div class="skill_secondary">
                        <h5>{{ skill_other.name }}</h5>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section id="timeline">
        <div id="experiences">
            <h4>Expériences professionnelles</h4>
            {% for experience_job in experiences.job %}
                {% include "cv/macros/experience.html" with experience=experience_job %}
            {% endfor %}
        </div>
        <div id="voluntaries">
            <h4>Bénévolat</h4>
            {% for experience_volunteering in experiences.volunteering %}
                {% include "cv/macros/experience.html" with experience=experience_volunteering %}
            {% endfor %}
        </div>
        <div id="formations">
            <h4>Formations / Diplômes</h4>
            {% for experience_education in experiences.education %}
                {% include "cv/macros/experience.html" with experience=experience_education %}
            {% endfor %}
        </div>
    </section>

    <div id="cvLinkContainer">
        {% spaceless %}
            {% if resume.linkedin %}
                <a href="{{ resume.linkedin }}" class="cvLink btn btn-yellow btn-icon-linkedin" title="Se rendre sur mon profil Linkedin">Mon Linkedin</a>
            {% endif %}
            {% if resume.pdf_file %}
                <a href="{{ resume.pdf_file.url }}" class="cvLink btn btn-yellow btn-icon-download" title="Télécharger mon Curriculum Vitae">Télécharger mon CV</a>
            {% endif %}
        {% endspaceless %}
    </div>
</section>

cv/templates/cv/sections/folio.html
<section id="folio">
    <h3>Quelles sont mes réalisations ?</h3>
    <section id="realisations">
        <h4>Projets réalisés</h4>
        <div class="realisations_container">
            {% for project in projects %}
                <div class="realisation collapsed">
                    <div class="realisation-header">
                        <h5>{{ project.name }}</h5>
                        <div class="links">
                            {% for link in project.links.all %}
                                <a href="{{ link.url }}" class='link'>{{ link.icon }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="realisation-body">
                        <p class="realisation-description">{{ project.description|linebreaksbr }}</p>
                        <div class="realisation-technologies">
                            {% for technology in project.technologies.all %}
                                <div class="realisation-technology">
                                    <h6>{{ technology.name }}</h6>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <button type="button" class="realisation-toggle">
                        <p>8</p>
                    </button>
                </div>
            {% endfor %}
        </div>
    </section><!--
    --><section id="github">
        <h4>Dépôts Github</h4>
        <div id="repositories">
            {% for repository in repositories %}
                <div class="repository">
                    <p class="summary">
                        <em class="stars"><mark>s</mark>{{ repository.stargazers_count }}</em>
                        <em class="forks"><mark>y</mark>{{ repository.forks_count }}</em>
                        {% if repository.language %}
                            <em class="language">{{ repository.language }}</em>
                        {% endif %}
                    </p>
                    <h5>
                        {% if repository.fork %}<mark>y</mark>{% endif %}
                        <a title="{{ repository.name }}" href="{{ repository.html_url }}">{{ repository.name }}</a>
                    </h5>
                    <p class="description">{{ repository.description|default_if_none:"" }}</p>
                </div>
            {% endfor %}
        </div>
    </section>
    <div id="folioLinkContainer">
        {% spaceless %}
            {% if resume.github %}
                <a href="{{ resume.github }}" class="folioLink btn btn-green btn-icon-github" title="Se rendre sur mon profil Github">Mon Github</a>
            {% endif %}
            {% if resume.docker %}
                <a href="{{ resume.docker }}" class="folioLink btn btn-green btn-icon-docker" title="Se rendre sur mon profil Docker hub">Mon Docker Hub</a>
            {% endif %}
        {% endspaceless %}
    </div>
</section>

cv/templates/cv/sections/header.html
<header>
    <div id="hgroup">
        <h1>{{ resume.fullname }}</h1>
        <h2>{{ resume.title }}</h2>
    </div>
    <nav>
        <a href="#home" class="smoothScroll blue" title="Accueil">Home</a>
        <a href="#folio" class="smoothScroll green" title="Voir mes réalisations">Folio</a>
        <a href="#cv" class="smoothScroll yellow" title="Voir mon curriculum vitae">CV</a>
        <a href="#contact" class="smoothScroll red" title="Me contacter">Contact</a>
    </nav>
</header>

cv/templates/cv/sections/home.html
<section id="home">
    <h3>Qui suis-je ?</h3>
    {% spaceless %}
        <img id="photo" src="{{ resume.photo.url }}" alt="Photo">
        <div id="presentation">
            {{ resume.summary | safe | linebreaksbr }}
        </div>
    {% endspaceless %}
</section>

cv/templates/cv/sections/modals.html
<div id="md-overlay"></div>